http:
  port: 8888
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: "*"
    paths: "/ip"
  authApi:
    host: "*"
    paths:
      - "/api/auth/*"
  distanceApi:
    host: "*"
    paths:
      - "/api/distance/*"
  routesApi:
    host: "*"
    paths:
      - "/api/routes/*"
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  authService:
    url: "http://localhost:8000"
  distanceService:
    url: "http://localhost:5002"
  routesService:
    url: "http://localhost:3000"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - authApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
              stripPath: true

  distancePipeline:
    apiEndpoints:
      - distanceApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: distanceService
              changeOrigin: true
              stripPath: true

  routesPipeline:
    apiEndpoints:
      - routesApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: routesService
              changeOrigin: true
              stripPath: true
